apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: t2xhcxsip-nodejs
  janus-idp.io/tekton: t2xhcxsip-nodejs
  backstage.io/kubernetes-id: t2xhcxsip-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: t2xhcxsip-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
